- name: Start Autosys on HOST1 first
  ansible.builtin.systemd:
    name: autosys
    state: started
  when: inventory_hostname == "host1"
  tags: start

- name: Start Autosys on HOST2 second
  ansible.builtin.systemd:
    name: autosys
    state: started
  when: inventory_hostname == "host2"
  tags: start
