- name: Check Autosys status
  hosts: autosys_hosts
  become: yes
  tasks:
    - name: Run status command
      ansible.builtin.shell: su - autosys -c "unisrvcntr status all"
      register: autosys_status
      tags: status

    - name: Display Autosys status
      ansible.builtin.debug:
        var: autosys_status.stdout