- hosts: host2
  serial: 1
  tasks:
    - name: Stop Autosys on HOST2 first
      ansible.builtin.systemd:
        name: autosys
        state: stopped
      tags: stop

- hosts: host1
  serial: 1
  tasks:
    - name: Stop Autosys on HOST1 second
      ansible.builtin.systemd:
        name: autosys
       
